# Generated by Django 5.2.17 on 2026-09-21 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_education_hobby'),
    ]

    operations = [
        migrations.AddField(
            model_name='education',
            name='certificate_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
